# Generated by Django 2.0.2 on 2018-02-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20180216_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='temperature',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
