# Generated by Django 2.0.2 on 2018-02-16 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_auto_20180216_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observation_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.ObservationPoint'),
        ),
    ]
